version: "3.8"

services:
  movie_db:
    container_name: movie-db
    image: postgres
    restart: always
    ports:
      - "1501:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: movie_db
      PGDATA: /var/lib/postgresql/data
    volumes:
        - db:/var/lib/postgresql/data

  auth_db:
    container_name: auth-db
    image: postgres:15.2-alpine
    restart: always
    ports:
      - "1502:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auth-db
      PGDATA: /var/lib/postgresql/data
    volumes:
      - auth_db:/var/lib/postgresql/data

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
#    environment:
#      - RABBITMQ_DEFAULT_USER=admin
#      - RABBITMQ_DEFAULT_PASS=admin
    ports:
      - "5672:5672" # AMQP protocol port
      - "15672:15672" # HTTP management UI

volumes:
  db:
  auth_db: