spring:
  application:
    name: movie-service

    #TODO: create database
  datasource:
    url: jdbc:postgresql://localhost:5555/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect