version: "3.8"

services:
  movie_db:
    container_name: movie-db
    image: postgres
    restart: always
    ports:
      - "5555:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      PGDATA: /var/lib/postgresql/data
    volumes:
        - db:/var/lib/postgresql/data

volumes:
  db: