version: "3.8"

services:
  movie_db:
    container_name: movie-db
    image: postgres
    restart: always
    ports:
      - "1501:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      PGDATA: /var/lib/postgresql/data
    volumes:
        - db:/var/lib/postgresql/data

  auth_db:
    container_name: auth-db
    image: postgres:15.2-alpine
    restart: always
    ports:
      - "1502:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auth-db
      PGDATA: /var/lib/postgresql/data
    volumes:
      - auth_db:/var/lib/postgresql/data

volumes:
  db:
  auth_db: